[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python3", "python3-pip", "python3-venv", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building Python FastAPI application...'",
  "python -c 'import main; print(\"App imported successfully\")'"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"